#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""SSOT helper: byte-exact section split, navigation INDEX, compact DIGEST, staleness check.

Usage:
  jw_ssot.py split  [project-root]   # split SSOT at '## ' headings into <generated_dir>/sections/
  jw_ssot.py digest [project-root]   # write <generated_dir>/DIGEST.md (TOC + first-paragraph excerpts, line-capped)
  jw_ssot.py check  [project-root]   # exit 0 if split/digest match current SSOT, 3 if stale

The canonical document stays a single editable file; everything here is a generated,
read-only view. Split sections concatenate back to the original byte-for-byte (verified).
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from jw_common import find_project_root, load_config, slugify  # noqa: E402

GENERATED_NOTE = "<!-- GENERATED by jahns-workflow (jw_ssot.py) — DO NOT EDIT. Edit the SSOT instead. -->"


def _ssot_path(root: Path, cfg: dict) -> Path:
    ssot = cfg.get("ssot")
    if not ssot:
        sys.exit("jw_ssot: no 'ssot' path in .jahns-workflow.yml")
    p = root / ssot
    if not p.is_file():
        sys.exit(f"jw_ssot: SSOT not found: {p}")
    return p


def _sections(text: str) -> list[tuple[str, int, str]]:
    """Split on level-2 headings. Returns [(heading, start_line_1based, content)]."""
    lines = text.splitlines(keepends=True)
    bounds: list[int] = [i for i, ln in enumerate(lines) if ln.startswith("## ")]
    sections: list[tuple[str, int, str]] = []
    prev = 0
    heading = "(preamble)"
    for b in bounds:
        if b > prev or prev == 0:
            chunk = "".join(lines[prev:b])
            if chunk:
                sections.append((heading, prev + 1, chunk))
        heading = lines[b].removeprefix("## ").strip()
        prev = b
    sections.append((heading, prev + 1, "".join(lines[prev:])))
    return sections


def _hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def split(root: Path) -> int:
    cfg = load_config(root)
    src = _ssot_path(root, cfg)
    text = src.read_text(encoding="utf-8")
    outdir = root / cfg["generated_dir"]
    secdir = outdir / "sections"
    secdir.mkdir(parents=True, exist_ok=True)
    for old in secdir.glob("*.md"):
        old.unlink()

    sections = _sections(text)
    assert "".join(c for _, _, c in sections) == text, "split is not byte-exact"

    index_rows = ["| § | Heading | Lines | Bytes | File |", "|---|---|---|---|---|"]
    for i, (heading, start, content) in enumerate(sections):
        fname = f"{i:02d}-{slugify(heading)}.md"
        (secdir / fname).write_text(content, encoding="utf-8")
        end = start + content.count("\n") - 1
        index_rows.append(
            f"| {i} | {heading} | {start}–{end} | {len(content.encode('utf-8'))} | [{fname}](sections/{fname}) |"
        )

    (outdir / "INDEX.md").write_text(
        f"""{GENERATED_NOTE}
# SSOT Index — `{cfg['ssot']}`

Read only the sections you need (cite by §-anchor / heading, never by line number).
Source hash: `{_hash(text)[:16]}`

{chr(10).join(index_rows)}
""",
        encoding="utf-8",
    )
    (outdir / ".hash").write_text(_hash(text), encoding="utf-8")
    print(f"split {len(sections)} sections -> {secdir}")
    return 0


def _first_paragraph(content: str) -> str:
    """First prose paragraph after the heading line (skips blank lines and code fences)."""
    lines = content.splitlines()
    para: list[str] = []
    in_fence = False
    for ln in lines[1:]:
        if ln.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if ln.strip():
            para.append(ln.strip())
        elif para:
            break
    return " ".join(para)


def digest(root: Path) -> int:
    cfg = load_config(root)
    src = _ssot_path(root, cfg)
    text = src.read_text(encoding="utf-8")
    max_lines = int(cfg.get("digest_max_lines", 150))
    sections = _sections(text)
    title = next((ln.removeprefix("# ").strip() for ln in text.splitlines() if ln.startswith("# ")), cfg["ssot"])

    def build(excerpt_chars: int) -> list[str]:
        out = [GENERATED_NOTE,
               f"# SSOT Digest — {title}",
               "",
               f"Compact orientation map of `{cfg['ssot']}`. For details read specific sections "
               f"via `{cfg['generated_dir']}/INDEX.md` — do not re-read the whole SSOT.",
               ""]
        for i, (heading, _, content) in enumerate(sections):
            if heading == "(preamble)":
                continue
            out.append(f"**§{i} {heading}**")
            if excerpt_chars:
                p = _first_paragraph(content)
                if p:
                    out.append(f"  {p[:excerpt_chars]}{'…' if len(p) > excerpt_chars else ''}")
            out.append("")
        return out

    for excerpt in (280, 120, 0):
        lines = build(excerpt)
        if len(lines) <= max_lines:
            break
    lines = lines[:max_lines]
    while lines and lines[-1].startswith("**§"):
        lines.pop()

    outdir = root / cfg["generated_dir"]
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "DIGEST.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {outdir / 'DIGEST.md'} ({len(lines)} lines)")
    return 0


def check(root: Path) -> int:
    cfg = load_config(root)
    src = _ssot_path(root, cfg)
    hash_file = root / cfg["generated_dir"] / ".hash"
    if not hash_file.is_file():
        print("stale: no generated views yet (run split + digest)")
        return 3
    if hash_file.read_text(encoding="utf-8").strip() != _hash(src.read_text(encoding="utf-8")):
        print("stale: SSOT changed since last split (run split + digest)")
        return 3
    print("up to date")
    return 0


def main() -> int:
    if len(sys.argv) < 2 or sys.argv[1] not in ("split", "digest", "check"):
        print(__doc__, file=sys.stderr)
        return 1
    root = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else find_project_root(Path.cwd())
    if root is None:
        print("jw_ssot: no initialized project found", file=sys.stderr)
        return 1
    return {"split": split, "digest": digest, "check": check}[sys.argv[1]](root)


if __name__ == "__main__":
    sys.exit(main())
